name: see output
on: workflow_dispatch

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"] # "3.8", "3.9", "3.10", "3.11"]
        poetry-version: ["1.7.1"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SECRET_TEST }}
        run: |
          example-command "$SUPER_SECRET"
